### ISSUE TITLE
Possible Indentation Issue on VS Code + Indentation Rainbow

### ISSUE THREAD

**Issue by homestar9** [mjclemente/api-wrapper-template#1] opened 2020-02-06 19:13 UTC
Matt, first of all, thank you for putting this wrapper template together and for the presentation you did at the CFML online meetup.  

When I execute ` apiwrapper scaffold` in Commandbox, the resulting wrapper CFC that gets created appears to have indentation issues.  I noticed them because I also use the VS Code plugin "Indentation Rainbow" which helps to highlight any irregularities in a file's indentation.  Here's a screenshot of what the CFC looks like in VS Code.  The red highlighted areas were flagged by Indentation Rainbow:

![image](https://user-images.githubusercontent.com/5341142/73969740-d14b6c80-48d0-11ea-8b50-3de3ab5d0d64.png)

Perhaps the file uses a combination of tabs and spaces which is why the indentation was flagged on so many lines? Or maybe it has something to do with how Commandbox automatically generates the file?

I did try adjusting the indentation type in VS Code from spaces to tabs but I didn't notice any difference.

Please let me know if you have any thoughts as to what could be throwing things off.  If you like, I would be happy to create a pull request with a revised version of `template.cfc.stub` to see if that fixes the issue.

**Comment by mjclemente** [comment] 2020-02-06 19:17
Ahh. Interesting. I'll have to install that VS Code plugin and take a look. 

My first guess, without looking, is that you're right about it being a combination of tabs and spaces. If you're willing to put together a revised version of the template stub and that fixes it, that would be awesome. If not, no worries. I'll try to take a look a bit later today when I get the chance. Thanks for pointing it out!

**Comment by homestar9** [comment] 2020-02-06 20:03
You're welcome.  I submitted a [pull request](https://github.com/mjclemente/api-wrapper-template/pull/2) for your review with some indentation/formatting tweaks. I am usually pretty generous with whitespace because I feel it helps legibility. I know not everyone shares this opinion so feel free to revert or change anything that you don't care for.

**Comment by mjclemente** [comment] 2020-02-06 22:50
Thanks for taking the time with this.

Please bear with me; I probably should have done this first, but I'm seeing a little strangeness, in that I can't reproduce the malformed with the tabs/spaces that you're seeing when I open the stub (or a generated cfc) with Indent Rainbow:
<img width="994" alt="image" src="https://user-images.githubusercontent.com/5348419/73984282-59983480-4906-11ea-9cf2-3bab0f05bf88.png">

I'm not doubting that you're getting the strange results. If I copy and paste from Github into an online text area, I can see the tab/space mix, so it's there. I just don't know why what I'm seeing in VSCode isn't what's ending up saved. It probably has to do with a strange way my .editorconfig is being applied. I'll keep trying to sort that out. Doesn't impact the PR. Just strange.

**Comment by mjclemente** [comment] 2020-02-07 02:09
Well, this had me totally confused for a while, but I _think_ I figured it out - let me know what you think.

I have my Tab Size in VSCode set to 2:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/5348419/73993570-8eb18080-4920-11ea-9e29-c08812f2529c.png">

I'm guess that yours is set to 4. This different confuses the Indent Rainbow extension, because there are places with 6 spaces, which works out evenly for me (3 tabs), but doesn't for you (1.5 tabs).

Now, I didn't find this at first, because I have another setting turned on - Detect Indentation. 
<img width="819" alt="image" src="https://user-images.githubusercontent.com/5348419/73993811-5d858000-4921-11ea-8dd0-0a2e8b03bce2.png">

This detects the indentation of the file (2 in my case), and uses that instead of your default Tab Size. In testing, I found that if I change my Tab Size to 4, I see the strange rainbow when Detect Indentation is off, but turning it on resolves the issue.

These are all settings that I didn't even realize existed (though perhaps I changed them at one point in time). I'm thinking that 4 is a more common approach to this than 2, so making that change is appropriate.

**Comment by homestar9** [comment] 2020-02-07 23:22
Yeah, you figured it out.  Switching the template to use an indentation value of 4 instead of 2 should make the file more compatible for people using either spaces or tabs.

I created a [new pull request](https://github.com/mjclemente/api-wrapper-template/pull/3) with less "Nadeliness". ;)  I did my best to keep as much of the original formatting as possible aside from indentation tweaks.   Of course, please feel free to edit as you see fit.

**Comment by mjclemente** [comment] 2020-02-08 01:03
Much appreciated! And thanks for your patience with me.

**Comment by mjclemente** [comment] 2020-02-08 01:06
Resolved with #3

**Closed as completed by mjclemente** 2020-02-08 01:06 UTC

**Comment by mjclemente** [comment] 2020-02-08 02:22
Rolled out the updated version. Let me know if you run into any further issues.
